name: threebotlogin
description: A decentralized login application

publish_to: 'none'

version: 4.0.0+180

environment:
    sdk: '>=2.12.0<3.0.0'

dependencies:
    flutter:
        sdk: flutter

    yggdrasil_plugin:
        git:
            url: https://github.com/threefoldtech/yggdrasil_flutter
            ref: main

    flutter_pkid:
        git:
            url: git@github.com:threefoldtech/flutter-pkid-client.git
            ref: main_null-safety

    redirection:
        git:
            url: https://github.com/jimbertools/redirection
            ref: main_null-safety

    qr_code_scanner:
        git:
            url: https://github.com/X-SLAYER/qr_code_scanner.git
            ref: flutter-beta

    flutter_svg: ^1.1.6
    bip39: ^1.0.6
    socket_io_client: ^2.0.0
    local_auth: ^2.1.2
    url_launcher: ^6.1.6
    shared_preferences: ^2.0.15
    http: ^0.13.5
    package_info: ^2.0.2
    cupertino_icons: ^1.0.4
    google_fonts: 2.2.0
    intl_phone_field: ^3.1.0
    flagsmith: ^3.0.3
    cryptography: ^2.0.5
    flutter_inappwebview: ^5.7.1
    flutter_sodium: ^0.2.0
    uni_links: ^0.5.1
    pbkdf2ns: ^0.0.2
    flutter_json_viewer: ^1.0.1
    device_info_plus: ^4.0.0
    open_filex: ^3.4.0

dev_dependencies:
    flutter_native_splash: ^2.2.14
    flutter_test:
        sdk: flutter

flutter_native_splash:
    color: '#FFFFFF'
    image: assets/logo.png
    android: true
    ios: true

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/
