apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "database.fullname" . }}
  name: {{ include "database.fullname" . }}
spec:
 
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: {{ include "database.fullname" . }}

