apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
data:
  mariadbUsername: {{ .Values.secret.mariadbUsername | b64enc | quote }}
  mariadbPassword: {{ .Values.secret.mariadbPassword | b64enc | quote }}
