ingress:
  hosts:
    - host:
        domain: frontend.minikube.local
        path: /api
        chart: backend
        service: dev-backend
    - host:
        domain: frontend.minikube.local
        path: /
        chart: frontend
        service: dev-frontend
    - host:
        domain: frontend.minikube.local
        path: /socket.io
        chart: backend
        service: dev-backend

global:
  FRONTEND_IMAGE: ""
  BACKEND_IMAGE: ""
  FLAGSMITH_API_KEY: ""
  DATABASE_URL: ""
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD: ""
  DOCKER_REGISTRY: "ghcr.io"
