apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      - path: {{ .host.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name}}-{{ .host.chart }}
            port:
              number: 443
{{- end }}


