apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  tls:
    - hosts:
        - login-beta.jimbertesting.be
      secretName: {{ template "releaseName" . }}
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      - path: {{ .host.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name}}-{{ .host.chart }}
            port:
              number: 80
{{- end }}
