apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.FULL_NAME" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.FULL_NAME" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.FULL_NAME" . }}
    spec:
      containers:
      - image: {{ include "backend.IMAGE" . }}
        imagePullPolicy: Always
        name: {{ include "backend.FULL_NAME" . }}
        ports:
        - name: http
          containerPort: 3001
        env:
          - name: "FLAGSMITH_API_KEY"
            value: {{ include "backend.FLAGSMITH_API_KEY" . }}
          - name: "DATABASE_URL"
            value: {{ include "backend.DATABASE_URL" . }}
