apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
data:
  mariadb-uri: {{ with .Values.secret -}}
  {{- list "mysql://" .mariadbUsername ":" .mariadbPassword  "@" $.Release.Name "-" .dbchart ":" .port "/" .dbconn | join "" |  quote }}
{{- end }}
