name: Production

# Controls when the workflow will run
on:
    push:
        tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
    build_frontend:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.image.outputs.lowercase }}
        permissions:
            contents: read
            packages: write
        env:
            REGISTRY: ghcr.io
            IMAGE_NAME: ghcr.io/repository/project/frontend
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - id: image
              uses: ASzc/change-string-case-action@v2
              with:
                  string: ${{ github.repository }}

            - name: Build and push
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.IMAGE_NAME }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: apps/web/Dockerfile
                  push: true
                  tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.ref_name}},${{ env.IMAGE_NAME }}:production-latest
                  labels: ${{ steps.meta.outputs.labels }}

    build_backend:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.image.outputs.lowercase }}
        permissions:
            contents: read
            packages: write
        env:
            REGISTRY: ghcr.io
            IMAGE_NAME: ghcr.io/repository/project/backend
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - id: image
              uses: ASzc/change-string-case-action@v2
              with:
                  string: ${{ github.repository }}

            - name: Build and push
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.IMAGE_NAME }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: apps/api/Dockerfile
                  push: true
                  tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.ref_name}},${{ env.IMAGE_NAME }}:production-latest
                  labels: ${{ steps.meta.outputs.labels }}

    deploy:
        runs-on: jimbertools-action-runner
        needs:
            - build_frontend
            - build_backend
        env:
            FRONTEND_IMAGE: ghcr.io/repository/project/frontend:${{ github.ref_name}}
            BACKEND_IMAGE: ghcr.io/repository/project/backend:${{ github.ref_name}}
            FLAGSMITH_URL: ${{ secrets.FLAGSMITH_URL }}
            FLAGSMITH_API_KEY: ${{ secrets.PRODUCTION_FLAGSMITH_API_KEY }}
            BACKEND_URL: /
            MARIADB_ROOT_PASSWORD: ${{ secrets.PRODUCTION_DATABASE_PASSWORD }}
        steps:
            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/checkout@v2
            - name: Down
              run: docker-compose -f docker-compose.production.yml down
            - name: Deploy
              run: docker-compose -f docker-compose.production.yml up -d
